#Autocomplete plugin config
#Thu Mar 17 12:16:35 UTC 2022
autocomplete.enabled=false
autocomplete.labels.actual=http\://www.w3.org/2000/01/rdf-schema\#label@
autocomplete.indexiris.configured=true
autocomplete.indexiris.actual=true
autocomplete.labels.configured=https\://data.coypu.org/country@\nhttps\://data.coypu.org/@\nhttp\://www.w3.org/2000/01/rdf-schema\#label@\nhttps\://schema.coypu.org/@
